### ISSUE TITLE
Random Chest Filling

### ISSUE THREAD

**Issue by Gaurav99** [SkyWars/SkyWars#117]
Hey - I have a feature suggestion.  Make it so that in an arena if there are chests they get randomly filled with items defined in a configuration file.  This would be a VERY good addition as it would increase the randomness of items spawning and wouldn't rig one spawn to win the entire game.

Thanks!
Gaurav

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I've closed several issues for the same thing, #134, #161 and #180.

Here are some ideas from them:
- Different chests have different sets of items
- Different item "levels" so that chests are more or less equal in strength but have different items.

**Comment by daboross** [comment]
This is now implemented!
