### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by fearink** [SkyWars/SkyWars#119]
hi i just installed this plugin and it is working great i was just wondering if there was a way to configure what is in the chests in the included map thanks :D

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I'll help more.

There should also be a better way to do this sometime in the future.
