### ISSUE TITLE
Dyed Leather Armor

### ISSUE THREAD

**Issue by DARKHAWX** [SkyWars/SkyWars#148]
Hi there,
Just noticed there seemed to be no way (or at least documentation of a way) to create kits that have dyed leather in them.
This would be really nice as a simple aesthetic thing but also as a way of creating team based kits.

Hopefully you read this and can add it as I would really like this.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

Since it's been abandoned, it's likely that you've switched plugins or are no longer using SkyWars.

In any case, this has now been added in https://github.com/SkyWars/SkyWars/commit/4f1272c770ad4b0812b4465b7f263fa83fddf4de and will be released in 2.1.1.
