### ISSUE TITLE
SkyWars timings

### ISSUE THREAD

**Issue by chrisbruijnes** [SkyWars/SkyWars#158]
Hey!

I have a small question about SkyWars. I did some timings from Spigot feature and saw this.

http://gyazo.com/e5d6b82dd9beeb6576bf84faf30b6390

Do you have any explaination?

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will investigate further.

Side note: this is probably fixed by switching to WorldEdit and using v2.1.0.
