### ISSUE TITLE
How to make a costly donator kit.

### ISSUE THREAD

**Issue by 003mikey** [SkyWars/SkyWars#181]
IM running a 1.7.9 bukkit server, and i cant seem to be able to make a costly donator kit. I dont really understand you intructions because they do not give detail

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will provide further help.

In general, for any future viewer: a costly donator kit just needs a donator permission, and a cost - then it will cost some amount, and only be usable by those with the permission.
