### ISSUE TITLE
Land too close

### ISSUE THREAD

**Issue by eijatk** [SkyWars/SkyWars#189]
I edited SkyWarsBaseWorld (using multiverse teleport) and added some stuff in the chests. That worked fine, I could see the new items in the arena when I started a new game. But... the land below the sky islands were so close that when a player dropped down from the island, he did not die. Instead he could wander around the land, even found a nice little village there with new chests and everything. 

How do I delete the land, so that there is only sky, and when you fell off the island, you die?

**Comment by eijatk** [comment]
Forgot to mention... When editing SkyWarsBaseWorld, there's no land there. The land only appears in an arena when a game is started.

**Comment by BloodshotPico** [comment]
You should have imported the world using multiverse then used a generator for the world. (Example: Load the server then use multiverse to load the world using a custom world generator plugin like VoidWorld)

**Comment by eijatk** [comment]
Thanks for the reply. But I don't quite understand... I used multiverse to import the world SkyWarsBaseWorld. When I edit it with the WorldEdit, it seems just fine. Only the blocks in the air are there, there IS NOT LAND in SkyWarsBaseWorld. But when the SkyWars game starts, there is land there. Where does it come from, isn't the arena loaded directly from SkyWarsBaseWorld. What am I missing here?

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will investigate further.

Just another note on this issue: I think the problem is probably that the SkyWars**Arena**World has a non-void generator. SkyWarsArenaWorld is the world where games actually take place - you'll probably need to import that one in multiverse.
