### ISSUE TITLE
Lobby Placement.

### ISSUE THREAD

**Issue by BloodshotPico** [SkyWars/SkyWars#190]
I'm wondering if you can set the lobby for the (certain) Arena in either one of the worlds provided or would it be better if I didn't?

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply and I will help further.

I'm also not quite sure what the concept of "lobby" would be - SkyWars's concept of a lobby is just the place for people to go once they've finished a game - I don't think it'd make sense to have it per-arena.
