### ISSUE TITLE
Chest Customization not working

### ISSUE THREAD

**Issue by Tball2** [SkyWars/SkyWars#210]
#### Issue / Bug / Crash:
I can't get my arena to work with custom chests.
server Version:
When did this issue occur?:
1.8.9
What did you expect to happen?:
The chests to fill with random items I followed the instructions on how to do so to the letter.
What happened?:
The chests remained empty
Output URL from `/SW report`:
https://gist.github.com/anonymous/b5cc31e312c2f66f84beac1b2d7167fd
Any errors in console?:
No errors in console
#### Feature Request:

What would you like to be added?:

**Comment by daboross** [comment]
Thank you for the detailed report!

Would it be possible for you to set `debug: true` in main-config.yml, start a game, and then pastebin and share the server log file? I think that would help a lot in telling what's going wrong.

**Comment by Tball2** [comment]
Will do. I'll send you that ASAP
Thank you

**Comment by daboross** [comment]
Does this still occur?

**Comment by daboross** [comment]
Since it's been a bit over a month since the last reply I've received from you, I'm going to assume that the issue no longer occurs or that you are no longer using SkyWars.

If the issue is still occurring, reply and I will definitely help. If you've solved the issue, it would be awesome if you could share what worked, so it could be added to the wiki.

Thanks!
