### ISSUE TITLE
SkyWars-API Documentation Request

### ISSUE THREAD

**Issue by Griffinator55** [SkyWars/SkyWars#211]
#### API Documentation Request:

I apologize for writing this issue here but I could not create an issue on the Skywars-API repository as you instructed to. I was wondering if I could possibly be given some documentation on how to get the players or number of players in que for a skywars game using your api?

**Comment by daboross** [comment]
Sure!

First thing you'll need is the [SkyWars](https://github.com/SkyWars/SkyWars-API/blob/master/src/main/java/net/daboross/bukkitdev/skywars/api/SkyWars.java) object, which is just the JavaPlugin object cast as SkyWars: `server.getPluginManager().getPlugin("SkyWars")`.

As long as the plugin is enabled, you should then be able to use `skywars.getGameQueue()` to get the [SkyGameQueue](https://github.com/SkyWars/SkyWars-API/blob/master/src/main/java/net/daboross/bukkitdev/skywars/api/game/SkyGameQueue.java) object, which handles the players waiting to get in the game.

After that, the SkyGameQueue object has a method `queue.getNumPlayersInQueue()` which will return an integer - this is the number of players currently queued waiting for the game.

It should be safe to store the `SkyWars` object permanently, but it'd probably be best to retrieve the `SkyGameQueue` once every time you need to get the number of players. The `SkyGameQueue` object will be the same while SkyWars is loaded, but if `/reload` is ever used or a plugin manager is used to reload SkyWars, a new `SkyGameQueue` is created and the old `SkyGameQueue` object will no longer give valid information.

I hope that's clear enough, if there are any other questions I'd be happy to answer!

**Comment by Griffinator55** [comment]
Thank You for responding so quickly to my request. I am running into an issue when I first try to get the SkyWars object. The object works without errors but when I am trying to get the GameQueue I am getting a error that the method `getGameQueue()` is undefined for the SkyWars Object. I feel like I am missing something completely obvious here but I can not seem to figure out what that is. Here is my current code : 
```
Object skyWars = (Object) Bukkit.getServer().getPluginManager().getPlugin("SkyWars");

	public void checkQueuedPlayers() {
		org.bukkit.Bukkit.getScheduler().scheduleSyncRepeatingTask(SkyWarsMenu.plugin, new Runnable() {
			@Override
			public void run() {
				Object queue = skyWars.getGameQueue();
				int inQue = ((Object) queue).getNumPlayersInQueue();
			}
		}, 240, 240);
	}
```

**Comment by daboross** [comment]
I think the problem here is that you need to cast skywars to the `SkyWars` class in order to use the methods - casting and storing as a plain Object won't tell the compiler what it needs to know. I'll write an example of this in just a second.

**Comment by daboross** [comment]
Here's a modified version of your example:


The problem here is that while it is true that the 'skyWars' object is an Object, you are trying to use a method which only exists for the 'SkyWars' interface. In order to use this method, you need to tell the compiler that you *know* that `skyWars` is a `SkyWars`:

```java
public class ... extends JavaPlugin {

    private SkyWars skywars;

    @Override
    public void onEnable() {
        Object skywarsObject = Bukkit.getServer().getPluginManager().getPlugin("SkyWars");
        if (skywarsObject instanceof SkyWars) {
            skywars = (SkyWars) skywarsObject;
        } else {
            getLogger().warning("Failed to load SkyWars class");
        }
    }

    public void checkQueuedPlayers() {
        org.bukkit.Bukkit.getScheduler().scheduleSyncRepeatingTask(SkyWarsMenu.plugin, new Runnable() {
            @Override
            public void run() {
                SkyGameQueue queue = skyWars.getGameQueue();
                int inQue = queue.getNumPlayersInQueue();
            }
        }, 240, 240);
    }
}
```

The two changes I've made are to check if `skywarsObject instanceof SkyWars` before setting a `SkyWars`-type variable to the plugin, and to store the 'queue' object as an instance of `SkyGameQueue` and not `Object`.

Note that in order to use the API, you will need to tell your compiler where these classes are defined (SkyWars-API.jar). If you use maven, I can show you how to add my repository. If you don't use maven, you can download the API jar from http://repo.dabo.guru/releases/net/daboross/bukkitdev/skywars-api/2.1.4/skywars-api-2.1.4.jar and the Javadoc jar (for in-IDE documentation of SkyWars-API) from http://repo.dabo.guru/releases/net/daboross/bukkitdev/skywars-api/2.1.4/skywars-api-2.1.4-javadoc.jar.

**Comment by Griffinator55** [comment]
Thanks a bunch for all the help.

**Comment by daboross** [comment]
No problem!
