### ISSUE TITLE
SkyWars will not delete inventory before when game starts

### ISSUE THREAD

**Issue by beversfi** [SkyWars/SkyWars#68]
SkyWars will not delete inventory before when game starts.   So when people join they have inventory they are not supposed to have. I am running SkyWars 1.4.
I do not see any place to configure this.  I was running 1.3.2 previously and it deleted the non-game inventory automatically when the game started but it will not do it now that I have upgraded to 1.4.

Thanks

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. @Peter234679, if you still use skywars and this still happens, please open a new issue.
