### ISSUE TITLE
chunks not unloading

### ISSUE THREAD

**Issue by anfereon** [SkyWars/SkyWars#72]
Why does this plugin keep all chunks loaded even when there is no player playing skywars? It uses so much ram for no reason. Would chunk unloading be so hard to implement?

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

Looking back at this issue though, I'm not entirely sure what the question/concern is. SkyWars does not keep multiple arenas loaded if they are not used right now - arenas are deleted immediately after the game is finished, and should not be kept loaded by the server. (SkyWars doesn't force the server to unload chunks, but it deletes all blocks and entities in them and makes no effort to keep the chunks loaded).

I'm going to assume since it's been abandoned, you've switched plugins or are no longer using SkyWars. If you still use SkyWars, just reply with more details and I'll re-open and help more.
