### ISSUE TITLE
Kit Effects

### ISSUE THREAD

**Issue by MrLooting** [SkyWars/SkyWars#75]
Ability to add potion effects to kits.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

If you are still using this plugin after it's period of inactivity, this feature has been added!

Potions can now be added to kits as of https://github.com/SkyWars/SkyWars/commit/4e21a74c5b0409cd023ee050751599e8a4b39d32.

**Comment by daboross** [comment]
My apologies for absence for quite a period of time, I did abandon the project. I'm not fully back but I am doing some work.

With SkyWars v2.1.0, support for potions with effects was added to kits. While that isn't *exactly* what this issue is, I think I'd rather keep the support level at supporting potions rather than directly applied potion effects.

If you are still using SkyWars, and you feel that the support I added didn't really satisfy this issue, please do reply and I will add more support!
